### ISSUE TITLE
Which Brand?

### ISSUE THREAD

**Issue by StuFull** [phenotypic/homebridge-web-shower#1]
Hi Tom,

Do you have any knowledge if this would work with a Quartz Touch shower from Aqualisa?

https://www.aqualisa.co.uk/quartz-touch.html

**Comment by phenotypic** [comment]
Hi there, unfortunately this plugin is not designed for a specific smart shower, and will require adaptation to work with product-specific APIs. You can see the current API expectations in the `README.md`.

You are more than welcome to fork and adapt the plugin such that it will work with the API of your device. Please note that this plugin is still under development, and is not yet completed nor tested.
