### ISSUE TITLE
Shows two shower heads

### ISSUE THREAD

**Issue by Casuallynoted** [phenotypic/homebridge-web-shower#2]
Hello!

I've been playing with this plugin, and have noticed that no matter how many zones I set it seems to have two shower heads named "Faucet 1" and "Faucet 2" in the faucet device. Is there a way to make it just the one faucet?

**Comment by Casuallynoted** [comment]
Whoops! Just fixed it by adding "heads": 1 to the config. Might be worth adding it to the readme just in case! One other issue I'm seeing though is that for some reason the main object is using the faucet icon rather than the regular shower icon.

**Comment by phenotypic** [comment]
Hi there, thanks for opening the issue. Unfortunately, as you can see from the README, this project is still under development and I am not actively maintaining it. Most of the README is currently copied from my [homebridge-web-sprinklers](https://github.com/Tommrodrigues/homebridge-web-sprinklers) plugin.

Overhauling the README and completing the functionality of the plugin is something I look to do in the near future. In the meantime, please feel free to fork the plugin and open a pull request!
